name: retail_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipython=8.25.0
  - traitlets=5.14.3
  - jupyterlab=4.2.5
  - notebook=7.2.2
  - ipykernel=6.29.5
  - ipywidgets=8.1.5
  - pandas=2.2.3
  - numpy=1.26.4
  - scipy=1.13.1
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - scikit-learn=1.5.2
  - statsmodels=0.14.3
  - plotly=5.22.0
  - python-dotenv=1.0.1
  - pyarrow=17.0.0
  - openpyxl=3.1.5
  - xlrd=2.0.1
  - lxml=5.3.0
  - tqdm=4.66.5
  - pip
  - pip:
      - kaleido==0.2.1
